version: '3'
services:
  mysql:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    volumes:
    - mysql-data:/var/lib/mysql
    command: mysqld --sql_mode=""
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
    - redis-data:/data
  mongo:
    image: mongo:4-xenial
    ports:
      - "27017:27017"
    volumes:
    - mongo-data:/data/db
volumes:
  mysql-data:
  redis-data:
  mongo-data:
